[package]
name = "kernel-qemu-virt"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "VeerOS kernel for the QEMU virt RISC-V 32-bit machine"

[features]
default = ["dist-minimal"]
dist-minimal = ["microkernel/dist-minimal"]
dist-app = ["microkernel/dist-app"]
dist-rt = ["microkernel/dist-rt"]
dist-full = ["microkernel/dist-full"]

[dependencies]
arch = { path = "../../arch" }
microkernel = { path = "../../microkernel", default-features = false }
soc-qemu-virt = { path = "../../soc/qemu_virt" }
net = { path = "../../net" }
shell = { path = "../../shell" }
smoltcp = { workspace = true }
panic-halt = "1.0"
