[alias]
check-all = "check --workspace --all-targets"
check-soc-esp32 = "check -p soc-esp32 --target riscv32imc-unknown-none-elf"
check-kernel-esp32c6 = "check -p kernel-xiao-esp32c6 --target riscv32imc-unknown-none-elf"
check-kernel-qemu = "check -p kernel-qemu-virt --target riscv32imc-unknown-none-elf"
check-kernel-raspi5 = "check -p kernel-raspi5 --target aarch64-unknown-none-softfloat"
build-esp32c6 = "build --release -p kernel-xiao-esp32c6 --target riscv32imc-unknown-none-elf"
build-qemu = "build --release -p kernel-qemu-virt --target riscv32imc-unknown-none-elf"
build-raspi5 = "build --release -p kernel-raspi5 --target aarch64-unknown-none-softfloat"
build-raspi5-minimal = "build --release -p kernel-raspi5 --target aarch64-unknown-none-softfloat --no-default-features --features dist-minimal,shell"
build-raspi5-rt = "build --release -p kernel-raspi5 --target aarch64-unknown-none-softfloat --no-default-features --features dist-full"