[package]
name = "microkernel"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[features]
default = ["dist-minimal"]
dist-minimal = []
dist-app = []
dist-rt = []
dist-xrt = ["dist-rt", "accel"]
dist-full = ["dist-app", "dist-xrt"]
dist-cluster = ["crypto/sha256", "crypto/chacha20", "crypto/ed25519"]
multi-user = []
ramfs-small = []
accel = ["dep:quantum"]

[dependencies]
bitflags.workspace = true
arch = { path = "../arch" }
crypto = { path = "../crypto" }
quantum = { path = "../quantum", default-features = false, features = ["simulator"], optional = true }