[package]
name = "microkernel"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[features]
default = ["dist-minimal"]
dist-minimal = []
dist-app = []
dist-rt = []
dist-full = ["dist-app", "dist-rt"]
multi-user = []
ramfs-small = []

[dependencies]
bitflags.workspace = true
arch = { path = "../arch" }
crypto = { path = "../crypto" }